### ISSUE TITLE
Example usage with bottomSheet

### ISSUE THREAD

**Issue by nebis-software** [robert-luoqing/flutter_user_guildance#2]
Hi,
    first of all, thanks for this package, it is really saving my  day!

Now the question: in my app the user can open a bottomSheet with some content (that covers 30% of the screen approx) , and I would like to add some guildance to its widgets.
When it opens, the guildance appears correctly, but it forces the bottomSheet to fill the full screen....

Do you have any suggestion on how to solve this? Thanks!!
Luigi

**Comment by robert-luoqing** [comment]
Please update to flutter_user_guildance: ^2.0.6. 

Detail please check https://github.com/robert-luoqing/flutter_user_guildance/blob/master/example/lib/test_bottom_sheet.dart

**Comment by nebis-software** [comment]
Thanks, that was fast!!!

I have tested the new version but I have a couple of issues. I am attaching here a modified version of your test_bottom_sheet.dart file that replicates the issues:

1) i have added a third step that with a widget very close to the bottom of the screen: on my test Android device, the tooltip is placed below it, i.e. outside the screen (i see only the initial part of the arrow)
2) i have added a non-modal bottom sheet: for the non-modal bottom sheet, only the bottom sheet itself is greyed out
3) for the non-modal bottom sheet, no tooltip is visible

This was tested using: flutter doctor
[✓] Flutter (Channel stable, 3.22.2, on Ubuntu 23.10 6.5.0-35-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.90.0)
[✓] Connected device (1 available)

[test_bottom_sheet.txt](https://github.com/user-attachments/files/15846341/test_bottom_sheet.txt)

Thanks!

**Comment by robert-luoqing** [comment]
Please update to flutter_user_guildance: ^2.0.7. 

If you are using bottom sheet or dialog, please set useModalAsMask to true. It can support these non-full screen UI.

```
    return UserGuidance(
        controller: userGuidanceController,
        showMaskWhenMissCondition: true,
        useModalAsMask: true,
        opacity: 0.5,
```

**Comment by nebis-software** [comment]
Thanks, it now works beautifully! Really appreciated
